### ISSUE TITLE
Create a sample unit test in typescript

### ISSUE THREAD

**Issue by cpoDesign** [ztolley/reacty#3]
as an advanced developer, I want to see a sample of a unit test using typescript where it is testing the actual component.

**Acceptance criteria**

- [ ] Create a sample component in typescript
- [ ] Create a unit test for the given component in typescript
- [ ] Unit test has to pass

**Comment by ztolley** [comment]
Will add this and later will add Cypress too, to demonstrate testing entire pages and business flows.

**Comment by ztolley** [comment]
#6
